package proyecto_tad.entity;
// Generated 11-may-2018 11:08:27 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Entrevista generated by hbm2java
 */
public class Entrevista implements java.io.Serializable {

     private Integer id;
     private int idEntrevistado;
     private int idEntrevistador;
     private String apto;
     private Date fecha;
     private String lugar;

    public Entrevista() {
    }

    public Entrevista(int idEntrevistado, int idEntrevistador, String apto, String lugar) {
        this.idEntrevistado = idEntrevistado;
        this.idEntrevistador = idEntrevistador;
        this.apto = apto;
        this.fecha = null;
        this.lugar = lugar;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getIdEntrevistado() {
        return this.idEntrevistado;
    }

    public void setIdEntrevistado(int idEntrevistado) {
        this.idEntrevistado = idEntrevistado;
    }

    public int getIdEntrevistador() {
        return this.idEntrevistador;
    }

    public void setIdEntrevistador(int idEntrevistador) {
        this.idEntrevistador = idEntrevistador;
    }

    public String getApto() {
        return this.apto;
    }
    
    public void setApto(String apto) {
        this.apto = apto;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getLugar() {
        return this.lugar;
    }

    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

}
