package proyecto_tad.entity;
// Generated 11-may-2018 11:08:27 by Hibernate Tools 4.3.1



/**
 * Entrevistador generated by hbm2java
 */
public class Entrevistador  implements java.io.Serializable {


     private Integer id;
     private String dni;
     private String nombre;
     private String departamento;

    public Entrevistador() {
    }

    public Entrevistador(String dni, String nombre, String departamento) {
       this.dni = dni;
       this.nombre = nombre;
       this.departamento = departamento;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    @Override
    public String toString() {
        return "Entrevistador{" + "id=" + id + ", nombre=" + nombre + '}';
    }




}


